import html2pdf from "html2pdf.js";

export const exportDocumentToPDF = (
  filename: string,
  title: string,
  content: string,
  metadata?: {
    referenceNumber?: string;
    ban?: string;
    status?: string;
    createdAt?: string;
  }
) => {
  const isDraft = metadata?.status?.toLowerCase().includes("draft");

  // DOM-based watermark: actual text elements at regular intervals so html2canvas captures them on every page
  const watermarkTiles = isDraft
    ? Array.from({ length: 80 }, (_, i) => {
        const top = i * 160;
        const left = i % 2 === 0 ? 40 : 220;
        return `<div style="position:absolute;top:${top}px;left:${left}px;transform:rotate(-35deg);font-size:54px;font-weight:bold;color:rgba(180,0,0,0.055);font-family:Arial,sans-serif;white-space:nowrap;letter-spacing:10px;pointer-events:none;user-select:none;z-index:0;">DRAFT</div>`;
      }).join("")
    : "";

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>${title}</title>
      <style>
        * { box-sizing: border-box; }
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 0; }
        .page-wrapper { position: relative; padding: 20px; }
        .watermark-layer { position: absolute; top: 0; left: 0; width: 100%; height: 100%; overflow: hidden; pointer-events: none; z-index: 0; }
        .content-layer { position: relative; z-index: 1; }
        .header { border-bottom: 2px solid #1e3a6e; padding-bottom: 15px; margin-bottom: 20px; }
        .header h1 { margin: 0 0 10px 0; font-size: 24px; color: #1e3a6e; }
        .metadata { background: #f5f7fa; padding: 12px; border-radius: 5px; margin-bottom: 20px; font-size: 12px; }
        .metadata-row { display: flex; justify-content: space-between; margin-bottom: 5px; }
        .metadata-label { font-weight: bold; color: #666; min-width: 100px; }
        .markdown-content { margin-top: 20px; font-size: 13px; white-space: pre-wrap; word-break: break-word; }
        .markdown-content h1, .markdown-content h2, .markdown-content h3 { color: #1e3a6e; margin-top: 15px; margin-bottom: 10px; }
        .markdown-content ul, .markdown-content ol { margin-left: 20px; }
        .markdown-content li { margin-bottom: 5px; }
        .markdown-content p { margin: 10px 0; }
        .footer { margin-top: 30px; padding-top: 15px; border-top: 1px solid #ddd; font-size: 10px; color: #999; text-align: center; }
      </style>
    </head>
    <body>
      <div class="page-wrapper">
        ${isDraft ? `<div class="watermark-layer">${watermarkTiles}</div>` : ""}
        <div class="content-layer">
          <div class="header"><h1>${escaped(title)}</h1></div>
          ${metadata ? `
          <div class="metadata">
            ${metadata.referenceNumber ? `<div class="metadata-row"><span class="metadata-label">Reference:</span><span>${escaped(metadata.referenceNumber)}</span></div>` : ""}
            ${metadata.ban ? `<div class="metadata-row"><span class="metadata-label">BAN:</span><span>${escaped(metadata.ban)}</span></div>` : ""}
            ${metadata.status ? `<div class="metadata-row"><span class="metadata-label">Status:</span><span>${escaped(metadata.status)}</span></div>` : ""}
            ${metadata.createdAt ? `<div class="metadata-row"><span class="metadata-label">Created:</span><span>${escaped(metadata.createdAt)}</span></div>` : ""}
          </div>` : ""}
          <div class="markdown-content">${escaped(content)}</div>
          <div class="footer">
            <p>Generated by the NBA Remuneration Portal</p>
            <p>Generated on ${new Date().toLocaleDateString("en-NG", { day: "numeric", month: "long", year: "numeric" })}</p>
          </div>
        </div>
      </div>
    </body>
    </html>
  `;

  const element = document.createElement("div");
  element.innerHTML = htmlContent;

  html2pdf().set({
    margin: 8,
    filename: `${filename}.pdf`,
    image: { type: "jpeg" as const, quality: 0.98 },
    html2canvas: { scale: 2 },
    jsPDF: { orientation: "portrait" as const, unit: "mm", format: "a4" },
  }).from(element).save();
};

function escaped(text: string): string {
  const div = document.createElement("div");
  div.textContent = text;
  return div.innerHTML;
}

function formDataToText(formData: unknown): string {
  if (!formData || typeof formData !== "object") return String(formData ?? "");
  return Object.entries(formData as Record<string, string>)
    .filter(([, v]) => v)
    .map(([k, v]) => `${k.replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase())}: ${v}`)
    .join("\n");
}

export const exportDocument = (doc: any) => {
  const filename = doc.reference_number || `document-${doc.id}`;
  const content = doc.content || formDataToText(doc.form_data);
  exportDocumentToPDF(filename, doc.title || "Legal Document", content, {
    referenceNumber: doc.reference_number,
    ban: doc.ban,
    status: doc.status === "completed" ? "Completed" : "Draft",
    createdAt: doc.created_at
      ? new Date(doc.created_at).toLocaleDateString("en-NG", { day: "numeric", month: "short", year: "numeric" })
      : undefined,
  });
};
